#!/bin/bash

connected_output=$(xrandr | grep " connected" | cut -f1 -d " ")

varset -s brghtnss $1

brightness=$(varset -g brghtnss)
raw_brightness=$(bc <<< "scale=2; $brightness/100")
xrandr --output "$connected_output" --brightness "$raw_brightness"

bar=$(tprogbar -v $brightness)
dunstify -r 5555 " $bar"
# xsetroot -name "  $bar"