#!/bin/bash

connected_output=$(xrandr | grep " connected" | cut -f1 -d " ")

tset -s brghtnss $1

brightness=$(tset -g brghtnss)
raw_brightness=$(bc <<< "scale=2; $brightness/100")
xrandr --output "$connected_output" --brightness "$raw_brightness"

bar=$(tprogbar -v $brightness)
# notify-send --hint=string:x-dunst-stack-tag:brghtnss "Brghtnss $bar" -t 1500
xsetroot -name "  $bar"
